baseURL = "https://tamada.github.io/pochi"
languageCode = "ja"
title = "Pochi"
hasCJKLanguage = "true"
enableEmoji = "true"
paginate = 6

theme = "hugo-xmag"
description = "The birthmarking platform."

[params]
    summary_length = 300
    description = "The birthmarking platform."
    footer = "&copy; Haruaki Tamada 2016--2017. <a href=\"http://tamada.github.com/\"><img src=\"/pochi/images/github.svg\" width=\"24\" /></a>  <a href=\"https://twitter.com/tama5\"><img src=\"/pochi/images/twitter.svg\" width=\"24\"></a>"

[params.banner]
    src = "/images/banner.svg"
    alt = "Pochi banner"

[params.text]
    about_author = "About the Author"
    author_delimiter = ", "
    back = "Back to Home"
    edit = "Edit this page"
    tags = "Tags: "
    truncated = " &hellip;"
    uncategorized = "Uncategorized"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Birthmarks"
    url = "/birthmarks"
    weight = 2
[[menu.main]]
    name = "Pochi"
    url = "/pochi"
    weight = 3
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"
    weight = 5

