baseURL = "https://tamada.github.io/pochi"
languageCode = "ja"
title = "Pochi"
hasCJKLanguage = "true"
enableEmoji = "true"
paginate = 6

theme = "hyde-hyde"

[params]
    themeColor = "theme-base-0e"
    authorimage = "/pochi/images/pochi.png"
    summary_length = 300
    highlightjs = true
    mathjax = true
    keywords = "birthmarks, Java, detecting the theft, plagiarism detection"
    description = "The software birthmarking platform for detecting the software theft."
    copyright = "(C) 2016 Haruaki Tamada."

[params.social]
    twitter = "tama5"
    github = "tamada"
    email = "tamada__at__cafebabe.jp"

[[menu.main]]
    name = "How to Use Pochi"
    identifier = "pochi"
    url = "/pochi/"
    weight = 200

[[menu.main]]
    weight = 100
    name = "What is Birthmarks?"
    identifier = "birthmarks"
    url = "/birthmarks/"
